---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ducklett
  namespace: kube-system
  labels:
    k8s-app: ducklett
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ducklett
subjects:
  - kind: ServiceAccount
    name: ducklett
