---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ducklett
  labels:
    k8s-app: ducklett
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["delete", "get", "update", "create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "delete"]
